model_list:
  - model_name: openai-gpt-3.5
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: sk-proj-...
      organization: org-...
      temperature: 0.2

litellm_settings:
  callbacks: pangea_litellm.proxy_handler_instance # sets litellm.callbacks = [proxy_handler_instance]
